# Shell variables
# Generated by 'wal'
wallpaper='/home/farokh/wallpaper/astronaut_jellyfish.jpg'

# Special
background='#0F161E'
foreground='#8ae1c1'
cursor='#8ae1c1'

# Colors
color0='#0F161E'
color1='#32514E'
color2='#595A59'
color3='#B85154'
color4='#30A95B'
color5='#B6A743'
color6='#94439B'
color7='#8ae1c1'
color8='#609d87'
color9='#32514E'
color10='#595A59'
color11='#B85154'
color12='#30A95B'
color13='#B6A743'
color14='#94439B'
color15='#8ae1c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
