--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/farokh/wallpaper/default.jpg"

-- Special
background="#0C1C29"
foreground="#dcd1cd"
cursor="#dcd1cd"

-- Colors
color0="#0C1C29"
color1="#5F5B69"
color2="#9A6861"
color3="#657389"
color4="#A38181"
color5="#B09D9B"
color6="#CE978E"
color7="#dcd1cd"
color8="#9a928f"
color9="#5F5B69"
color10="#9A6861"
color11="#657389"
color12="#A38181"
color13="#B09D9B"
color14="#CE978E"
color15="#dcd1cd"
