# Shell variables
# Generated by 'wal'
wallpaper='/home/farokh/wallpaper/default.jpg'

# Special
background='#0C1C29'
foreground='#dcd1cd'
cursor='#dcd1cd'

# Colors
color0='#0C1C29'
color1='#5F5B69'
color2='#9A6861'
color3='#657389'
color4='#A38181'
color5='#B09D9B'
color6='#CE978E'
color7='#dcd1cd'
color8='#9a928f'
color9='#5F5B69'
color10='#9A6861'
color11='#657389'
color12='#A38181'
color13='#B09D9B'
color14='#CE978E'
color15='#dcd1cd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
